mystring = input()
print(mystring[2])
print(mystring[-2])
print(mystring[:5])
print(mystring[:-2])
print(mystring[::2])
print(mystring[1::2])
print(mystring[::-1])
print(mystring[-1::-2])
print(len(mystring))